spring:
  profiles:
    active: main
  
  datasource:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://192.168.137.2:5432/postgres
      username: postgres
      password: qudgh1!

mybatis:
  mapper-locations: classpath:mapper/postgres/*.xml
  type-aliases-package: com.treeview.springboot.domain;
  configuration:
    map-underscore-to-camel-case: true  
